go-db-sql-final (stage1)
muslite/go-db-sql-final pull request #1
Opened 2024-11-24 17:15 UTC by muslite

2024-11-24 20:24 UTC, dirtymew requested changes
Привет Евгений

хорошая работа - но есть замечания которые нужно исправить

2024-11-24 20:24 UTC, dirtymew commented on parcel.go
> +		fmt.Println(err)
в функции main уже печатаются ошибки

2024-11-24 20:24 UTC, dirtymew commented on parcel.go
> +		return p, err
лучше явно вернуть пустую структуру

2024-11-24 20:24 UTC, dirtymew commented on parcel.go
> +	}
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-11-24 20:24 UTC, dirtymew commented on parcel.go
> +	row := s.db.QueryRow("SELECT status FROM parcel WHERE number=:number", sql.Named("number", number))
тут не очень оптимальное решение

у тебя 2 вызова к бд - а тут можно все сделать одним UPDATE

2024-11-24 20:24 UTC, dirtymew commented on parcel.go
> +	row := s.db.QueryRow("SELECT status FROM parcel WHERE number=:number", sql.Named("number", number))
тот же замечание что и к SetAddress

2024-11-24 20:24 UTC, dirtymew commented on parcel.go
> +	fmt.Println("fuunc Delete", number)
ну все запросы печатать не очень хорошо и главное вопрос зачем?

2024-11-24 20:24 UTC, dirtymew commented on parcel_test.go
> +	if err != nil {
тут не  нужно условие 

просто require.NoError(t, err)

2024-11-24 20:24 UTC, dirtymew commented on parcel_test.go
> +	assert.Equal(t, parcel.Address, res.Address)
проще проверить структуры чем каждое поле

2024-11-24 20:24 UTC, dirtymew commented on parcel_test.go
> +	require.Error(t, err)
тут еще хорошо бы проверить свою ошибку

например assert.ErrorIs

2024-11-24 20:24 UTC, dirtymew commented on parcel_test.go
> +	require.Equal(t, newAddress, res.Address)
assert

2024-11-24 20:24 UTC, dirtymew commented on parcel_test.go
> +	require.Equal(t, newStatus, res.Status)
assert

2024-11-24 20:24 UTC, dirtymew commented on parcel_test.go
> +	require.Equal(t, len(parcels), len(storedParcels))
assert.Len

2024-11-24 20:24 UTC, dirtymew commented on parcel_test.go
> +		assert.Equal(t, parcelMap[id].Address, parcel.Address)
assert.Equal(t, parcelMap[id], parcel)

2024-11-25 05:27 UTC, muslite commented on parcel.go
> +	row := s.db.QueryRow("SELECT status FROM parcel WHERE number=:number", sql.Named("number", number))
согласен, одним запросом много проще.

2024-11-25 05:35 UTC, muslite commented on parcel_test.go
> +	require.Equal(t, newAddress, res.Address)
+

2024-11-26 04:34 UTC, muslite commented
Благодарю. 
Скорее ужасная работа, коль скоро столько замечаний.  Прошу прощения. 
Убрал отладочную информацию, ненужные/дублирующие сообщения в функциях.
UPDATE, DELETE одним вызовом много проще и компактнее чем несколько. Благодарю. 

 
с assert.Equal(t, parcelMap[id], parcel) где то в теории напоролся на то что предложенное "каноническое" решение было в виде сравнения каждого значения. ( мое решение было  сравнивать ответ целиком)  Потому и здесь разобрал на части.

2024-11-26 11:48 UTC, dirtymew commented
> Благодарю. Скорее ужасная работа, коль скоро столько замечаний. Прошу прощения. Убрал отладочную информацию, ненужные/дублирующие сообщения в функциях. UPDATE, DELETE одним вызовом много проще и компактнее чем несколько. Благодарю.

Да нет - замечаний не много) 

про UPDATE - это не про компактность, а про оптимизацию. Иногда без доп вызовов к бд не обойтись ...


> с assert.Equal(t, parcelMap[id], parcel) где то в теории напоролся на то что предложенное "каноническое" решение было в виде сравнения каждого значения. ( мое решение было сравнивать ответ целиком) Потому и здесь разобрал на части.

ну раз у нас структуры без поинтеров в полях, то их можно сравнивать и стоит знать о такой особенности языка

2024-11-26 11:49 UTC, dirtymew approved these changes
Привет Евгений

все ок 

зачет

2024-11-26 11:49 UTC, dirtymew commented on parcel_test.go
> +	if err != nil {
@muslite забыл убрать условие - обрати внимание

2024-11-26 11:49 UTC, dirtymew commented on parcel_test.go
> +		assert.Equal(t, parcelMap[parcel.Number], parcel)
тут можно лучше в testify есть функции для работы с массивами - можно обойтись без цикла и мапы тут и все проверить одним assert-ом

2024-11-26 12:43 UTC, merged